[package]
name = "escrow-contract"
version = "0.1.0"
authors = ["baturalp"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "0.55.0"


[dev-dependencies]
multiversx-sc-scenario = "0.55.0"

[workspace]
members = [".", "meta"]