[package]
name = "escrow-contract"
version = "0.1.0"
authors = ["hanifi"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
multiversx-sc = "0.55.0"

[dev-dependencies]
multiversx-sc-scenario = "0.55.0"

[workspace]
members = [".", "meta"]
